name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run test suite
        run: npm test
        if: matrix.node-version != '22.x'

      - name: Run coverage suite
        run: npm run test:instrument
        if: matrix.node-version == '22.x'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.node-version == '22.x' && github.repository == 'jymfony/kumis'
        with:
          files: ./coverage/lcov.info
          flags: node-22
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
